FROM microsoft/dotnet:2.2-sdk-alpine3.8 AS build
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine3.8 AS base
WORKDIR /app
COPY --from=build /app/out .

CMD dotnet Softplayer.Calculadora.dll --urls "http://*:$PORT"
